# -*- coding: utf-8 -*-
"""KULLM3_최종 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfXJ2JPTtcsbvmK4Leda_tSx3vFEnCtk
"""

pip install peft

pip install -U bitsandbytes

import torch.nn.functional as F
import torch
import pandas as pd
from transformers import ElectraForSequenceClassification, ElectraTokenizer, AutoModelForCausalLM, AutoTokenizer, AdamW, Trainer, TrainingArguments
import transformers
from peft import LoraConfig, get_peft_model
from torch.utils.data import Dataset

MODEL_DIR = "nlpai-lab/KULLM3"
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)

# LoRA 설정
lora_config = LoraConfig(
    r=8,# 저차원 행렬의 차원 수
    lora_alpha=32, # 가중치 조정
    target_modules=["self_attn.q_proj", "self_attn.k_proj", "self_attn.v_proj"],# LoRA 적용할 모델의 특정 모듈 지정
    lora_dropout=0.05, # 드롭아웃 비율
    bias="none", # bias 사용 X
    task_type="CAUSAL_LM"
)

# 모델 로드
model = AutoModelForCausalLM.from_pretrained(MODEL_DIR, torch_dtype=torch.float16).to("cuda")
model = get_peft_model(model, lora_config) # LoRA 적용

# 데이터 로드
data = pd.read_excel('/content/sample_data/KcELECTRA_제목전처리X_수치화_전체.xlsx')
data = data[data['선정성 수치'] < 0.50]
data = data.dropna(subset=['본문', '제목'])  # NaN 값 제거
data = data[['제목', '본문']]

texts = data['본문'].tolist()  # 기사 본문
titles = data['제목'].tolist()  # 제목

class ArticleDataset(Dataset):
    def __init__(self, texts, titles, tokenizer, max_length=512):
        self.texts = texts
        self.titles = titles
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self): # 데이터셋 길이
        return len(self.texts)

    def __getitem__(self, idx): # 데이터 항목 접근
        text = self.texts[idx]
        title = self.titles[idx]

        # 본문 인코딩
        encoding = self.tokenizer(
            text,
            truncation=True, # 최대 길이 초과하면 자름 (512토큰 초과 시)
            padding='max_length', # 최대 길이에 맞춰 패딩 추가
            max_length=self.max_length,
            return_tensors='pt' # PyTorch tensor 형식으로 반환
        )

        # 제목 인코딩
        target_encoding = self.tokenizer(
            title,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        labels = target_encoding['input_ids'].flatten() # 제목 인코딩 결과에서 input_ids 가져옴 -> 1차원 평탄화
        labels[labels == 0] = -100  # padding 부분을 -100으로 설정

        return {
            'input_ids': encoding['input_ids'].flatten(), # 본문 텍스트 인코딩 결과
            'attention_mask': encoding['attention_mask'].flatten(), # 패딩 고려한 어텐션 마스크
            'labels': labels # 제목 인코딩 결과
        }

# 데이터셋 생성
dataset = ArticleDataset(texts, titles, tokenizer)

# Trainer 설정
training_args = TrainingArguments(
    per_device_train_batch_size=4,  # 배치 크기
    gradient_accumulation_steps=1,   # 기울기 누적 단계
    max_steps=500,                    # 학습 단계 수
    learning_rate=1e-4,              # 학습률
    fp16=True,                       # Mixed precision
    logging_steps=100,                # 로그 출력 주기
    output_dir="outputs",            # 출력 디렉토리
    optim="paged_adamw_8bit",        # 8비트 최적화
)

# Trainer 초기화
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

# 학습 시작
model.config.use_cache = False  # 경고를 없애기 위해 설정
trainer.train()

# 모델을 평가 모드로 설정
model.eval()
model.config.use_cache = True

def gen(text, title):
    # 토크나이즈하고 GPU로 이동
    inputs = tokenizer(
        f"본문에 맞게 제목을 비선정적으로 수정해줘:\n\n본문: {text}\n\n현재 제목: {title}\n\n새로운 제목:",
        return_tensors='pt',
        return_token_type_ids=False
    ).to('cuda')  # GPU로 이동

    gened = model.generate(
        **inputs,
        max_new_tokens=70,# 생성할 최대 토큰 수
        early_stopping=True, # 조기 종료 활성화
        do_sample=False, # 가장 높은 확률의 토큰 선택하여 생성
        eos_token_id=2, # 생성된 텍스트의 끝 토큰 ID
    )

    # 생성된 제목을 반환
    return tokenizer.decode(gened[0], skip_special_tokens=True)

# 데이터 로드
test_data = pd.read_excel('/content/sample_data/제목전처리O_수치화_상위100개.xlsx')
test_data = test_data.dropna(subset=['본문', '제목'])  # NaN 값 제거

# '본문'과 '제목'을 함께 사용하여 새로운 제목 생성
test_data['새로운 제목'] = test_data.apply(lambda row: gen(row['본문'], row['제목']), axis=1)

# '\n\n제목:' 이후의 텍스트만 남기기
test_data['새로운 제목'] = test_data['새로운 제목'].str.split('\n\n새로운 제목:').str[1]

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
test_data = pd.read_excel('/content/sample_data/output.xlsx')
test_data

import locale

# UTF-8 인코딩 설정
locale.getpreferredencoding = lambda: "UTF-8"

!pip install pandas transformers bert-score

from bert_score import score

# BERTScore 계산 함수
def calculate_bertscore(row):
    P, R, F1 = score([row['새로운 제목']], [row['본문']], lang='ko', verbose=False)
    return F1.item()

# 각 행에 대해 BERTScore 계산
test_data['BERTScore'] = test_data.apply(calculate_bertscore, axis=1)

test_data

test_data['BERTScore'].describe()

####################################################################################333

import torch.nn.functional as F
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_save_path = '/content/drive/MyDrive/2024/saved_model/KcELECTRA_Ver2'

# 1. 모델과 토크나이저 불러오기
model = AutoModelForSequenceClassification.from_pretrained(model_save_path)
tokenizer = AutoTokenizer.from_pretrained(model_save_path)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.eval()
model.to(device)

# data = pd.read_excel('/content/KULLM_전처리O_score.xlsx')

titles = test_data['새로운 제목'].astype(str).tolist()

def predict_probabilities(title):
    # 입력 텍스트를 토큰화
    inputs = tokenizer(title, return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)

    # 모델로 예측 수행
    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)  # 소프트맥스 적용

    # '1' 클래스(선정성) 확률 반환
    return probabilities[0][1].item()

# 제목별 선정성 확률 계산
test_data['새 선정성 확률'] = test_data['새로운 제목'].apply(predict_probabilities)

test_data

test_data['새 선정성 확률'].describe()

# 결과를 새로운 엑셀 파일로 저장
test_data.to_excel('KULLM_비선정_전처리O_final.xlsx', index=False)  # 저장할 파일 이름 지정

######################################################################################

import torch
import pandas as pd
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_DIR = "nlpai-lab/KULLM3"
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)

# 모델 로드 (LoRA 적용 없이)
model = AutoModelForCausalLM.from_pretrained(MODEL_DIR, torch_dtype=torch.float16).to("cuda")

model.eval()
model.config.use_cache = True

# def gen(text, title):
#     # 토크나이즈하고 GPU로 이동
#     inputs = tokenizer(
#         f"본문에 맞게 제목을 비선정적으로 수정해줘:\n\n본문: {text}\n\n현재 제목: {title}\n\n새로운 제목:",
#         return_tensors='pt',
#         return_token_type_ids=False
#     ).to('cuda')  # GPU로 이동

#     gened = model.generate(
#         **inputs,
#         max_new_tokens=70,  # 생성할 최대 토큰 수
#         early_stopping=True,  # 조기 종료 활성화
#         do_sample=False,  # 가장 높은 확률의 토큰 선택하여 생성
#         eos_token_id=2,  # 생성된 텍스트의 끝 토큰 ID
#     )

#     # 생성된 제목을 반환
#     return tokenizer.decode(gened[0], skip_special_tokens=True)

def gen(text, title):
    # 프롬프트 설정
    prompt = (
        f"현재 제목: {title}\n\n"
        f"본문: {text}\n\n"
        "**프롬프트 제목:** 선정적인 헤드라인을 비선정적인 헤드라인으로 변환하기\n\n"
        "**설명:** 아래는 선정적인 헤드라인과 비선정적인 헤드라인의 예시입니다. 이후에 제공하는 제목을 참고하여 선정적이지 않고 본문 내용과 일치하는 비선정적인 헤드라인으로 재작성해 주세요.\n\n"
        "1. **선정적인 헤드라인 예시 10개:**\n"
        "   - (예시 1) \"미녀 쫓아가 엉덩이 만지작 男, 사타구니 '퍽' 가격 당했다\"\n"
        "   - (예시 2) \"'손으로 가슴 만져줘' 알몸박스女 이곳저곳 출몰하더니 결국\"\n"
        "   - (예시 3) \"임창정♥서하얀, 노래방서 첫 키스 '청포도 먹여주다…가슴 터질 뻔'\"\n"
        "   - (예시 4) \"‘애마부인’ 안소영 '남동생이 누드사진 찍어줘…목욕할 때 등도 밀어준다'\"\n"
        "   - (예시 5) \"장윤주 '남편과 첫 만남 때 노브라 상태로 팔짱끼면서 가슴 밀착' 화끈 고백\"\n"
        "   - (예시 6) \"'1000만원 주면 알몸으로 테이블 올라갈게'…식당서 내기하고 홀딱 벗은 공무원들의 최후\"\n"
        "   - (예시 7) \"껴안고 엉덩이 '주물럭'…女외노자들만 노린 50대 공장장\"\n"
        "   - (예시 8) \"‘애마부인’ 안소영 “올 누드로 안장 없이 말 타다 하혈”\"\n"
        "   - (예시 9) \"'벗은 줄 알고 놀랐어' 현아♥이던, 누드톤 내의 입고 이불 위에서 '찰칵’\"\n"
        "   - (예시 10) \"적나라하게 비치는 엉덩이...카일리 제너, '완벽 S자' 몸매 드러내\"\n"
        "   - ...\n\n"
        "2. **비선정적인 헤드라인 예시 10개:**\n"
        "   - (예시 1) \"저출산 원인이 경제력 낮은 남자들 결혼 못 해서?\"\n"
        "   - (예시 2) \"성희롱 징계받고 취소 소송낸 상태에서 정년퇴직한 공무원\"\n"
        "   - (예시 3) \"광주지역 고3학생, 코로나19 상황에서도 성적 우수\"\n"
        "   - (예시 4) \"4752명, 이 숫자가 한 해 동안 미국에서 총에 맞아 죽은 미성년자 수라고요?\"\n"
        "   - (예시 5) \"임대차3법 개편, '전월세 대란' 논란 잠재울까\"\n"
        "   - (예시 6) \"만취차량에 다리 잃은 60대 환경미화원...가해자는 불구속 수사?\"\n"
        "   - (예시 7) \"코로나 19로 신음하는 이웃, 지구 반대편에도 있어\"\n"
        "   - (예시 8) \"삼성전자 반도체 임직원도 허리띠 졸라맸다…연봉 동결\"\n"
        "   - (예시 9) \"세븐틴 민규, 극심한 허리 통증으로 이번 주 일정 불참\"\n"
        "   - (예시 10) \"구미 아파트서 40대 여성 추락사\"\n"
        "   - ...\n\n"
        "**규칙:**\n"
        "- 주어진 헤드라인을 비선정적이고 중립적인 표현으로 재작성할 것.\n"
        "- 헤드라인이 본문의 핵심 내용을 반영하도록 작성하며, 본문의 주요 정보와 의미가 보존되도록 할 것.\n"
        "- 선정적이지 않은 언어와 표현을 사용할 것.\n\n"
        "**추가 지침:**\n"
        "- 한 번에 10개의 비선정적인 헤드라인 후보를 생성합니다.\n"
        "- 각 후보가 3가지 규칙을 모두 충족하는지 확인하고, 가장 적합한 헤드라인을 선택합니다.\n"
        "- 만약 10개의 후보가 모두 3가지 규칙을 충족하지 못하면 새로운 10개의 후보 헤드라인을 생성합니다.\n"
        "- 이 과정을 최적의 헤드라인이 나올 때까지 반복합니다.\n\n"
        "새로운 제목 후보:\n"
    )

    while True:
        # 토크나이즈하고 GPU로 이동
        inputs = tokenizer(
            prompt,
            return_tensors='pt',
            return_token_type_ids=False,
            truncation=True,  # 토큰을 자르기
            max_length=1024000000000000   # 최대 길이 지정
        ).to('cuda')  # GPU로 이동

        # 제목 후보 생성
        gened = model.generate(
            **inputs,
            max_new_tokens=30000000000000,  # 10개의 제목 생성 시 충분한 토큰 수 확보
            early_stopping=True,  # 조기 종료 활성화
            do_sample=False,  # 가장 높은 확률의 토큰 선택하여 생성
            eos_token_id=2,  # 생성된 텍스트의 끝 토큰 ID
        )

        # 프롬프트 이후의 텍스트만 디코딩
        generated_text = tokenizer.decode(gened[0], skip_special_tokens=True)

        # 10개의 후보 추출 (개행 문자 기준으로 분할)
        candidates = [line.strip() for line in generated_text.split('\n') if line.strip()]

        # 각 후보가 규칙을 충족하는지 확인 (간단한 필터링)
        valid_candidates = [candidate for candidate in candidates if all([
            "선정적" not in candidate,  # 선정적이지 않은지 단순히 확인
            len(candidate) > 0,  # 빈 제목이 아닌지 확인
        ])]

        # 유효한 후보가 있을 경우 반환
        if valid_candidates:
            return valid_candidates[0]  # 첫 번째 유효 후보 반환

# 데이터 로드
test_data = pd.read_excel('/content/sample_data/KcELECTRA_제목전처리X_수치화_상위10개.xlsx')
test_data = test_data.dropna(subset=['본문', '제목'])  # NaN 값 제거

# '본문'과 '제목'을 함께 사용하여 새로운 제목 생성
test_data['새로운 제목'] = test_data.apply(lambda row: gen(row['본문'], row['제목']), axis=1)

test_data

output_path = '/content/sample_data/example.xlsx'
test_data.to_excel(output_path, index=False)

# '\n\n제목:' 이후의 텍스트만 남기기
test_data['새로운 제목'] = test_data['새로운 제목'].str.split('새로운 제목 후보:').str[1]

test_data

import locale

# UTF-8 인코딩 설정
locale.getpreferredencoding = lambda: "UTF-8"

!pip install pandas transformers bert-score

from bert_score import score

# BERTScore 계산 함수
def calculate_bertscore(row):
    P, R, F1 = score([row['새로운 제목']], [row['본문']], lang='ko', verbose=False)
    return F1.item()

# 각 행에 대해 BERTScore 계산
test_data['BERTScore_final'] = test_data.apply(calculate_bertscore, axis=1)

test_data

from google.colab import drive
drive.mount('/content/drive')

import torch.nn.functional as F
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_save_path = '/content/drive/MyDrive/2024/saved_model/KcELECTRA_Ver2'

# 1. 모델과 토크나이저 불러오기
model = AutoModelForSequenceClassification.from_pretrained(model_save_path)
tokenizer = AutoTokenizer.from_pretrained(model_save_path)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.eval()
model.to(device)

title = test_data['새로운 제목'].astype(str).tolist()

def predict_probabilities(title):
    # 입력 텍스트를 토큰화
    inputs = tokenizer(title, return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)

    # 모델로 예측 수행
    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)  # 소프트맥스 적용

    # '1' 클래스(선정성) 확률 반환
    return probabilities[0][1].item()

# 제목별 선정성 확률 계산
test_data['새 선정성 확률'] = test_data['새로운 제목'].apply(predict_probabilities)

test_data

# 결과를 새로운 엑셀 파일로 저장
test_data.to_excel('KULLM3_제로샷_제목전처리X_수치화_최종.xlsx', index=False)  # 저장할 파일 이름 지정

#####################################

test_data = pd.read_excel('/content/KULLM_제로샷_전처리O_final.xlsx')

test_data['BERTScore'].describe()

test_data['새 선정성 확률'].describe()

